
trigger:
- master

pool:
  vmImage: windows-latest

variables:
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'src/Telligent.Rest.SDK.sln'
    feedsToUse: 'select'
    vstsFeed: 'af66e256-9c46-4fba-ad75-09bf110ec1cc'

- task: VSBuild@1
  inputs:
    solution: 'src/Telligent.Rest.SDK.sln'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'